version: '2.0'

services:
  mysql-docker-container:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=WishlistService
    ports:
      - 3306:3306
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  wishlist-app:
    image: manisha2506/wishlist
    depends_on:
      - mysql-docker-container
    ports:
      - 8080:8080
    volumes:
      - /data/wishlist-app    
